### ISSUE TITLE
Turn `const`s in data module into specs `Resource`s

### ISSUE THREAD

**Issue by monospacedmagic** [Skytrias/everpuzzle#38]
It's cleaner that way, isn't it?

specs `Resource`s: [Book](https://slide-rs.github.io/specs/04_resources.html) | [Docs](https://docs.rs/specs/latest/specs/struct.Resources.html)

**Comment by Skytrias** [comment]
Yeah so i tried adding the data as resources but it doesnt work for the projects purpose. I would simply want constants that stay the same and that dont have to initialized at any point. Thats the problem with resources - and also that only systems or functions via world can access resource data...

I think for now anyone really interested in changing hardcoded values can do so via changing the data manually and rebuild the game themselves. 

It also makes sense to not allow constants to be changed for mulitplayer, every player should abide by the same constants
